USE db_zoo
GO

CREATE TABLE tbl_ELECTRONICS (
	PRODUCT_Random_Id VARCHAR(50) PRIMARY KEY NOT NULL,
	PRODUCT_Id VARCHAR(50) PRIMARY KEY NOT NULL,
	PRODUCT_Brand INT NOT NULL,
	PRODUCT_Categories INT NOT NULL,
	PRODUCT_Colors INT NOT NULL,
	PRODUCT_DateAdded INT NOT NULL,
	PRODUCT_DateUpdated INT NOT NULL,
	PRODUCT_Dimensions INT NOT NULL,



);
